env:
  global:
    - TERM=dumb
    - GIT_AUTHOR_NAME="Valentin Boettcher"
    - GIT_AUTHOR_EMAIL="vale981@gmx.de""
    - GIT_COMMITTER_NAME="Valentin Boettcher"
    - GIT_COMMITTER_EMAIL="vale981@gmx.de"

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y texlive texlive-latex-extra texlive-generic-extra texlive-xetex texlive-lang-german fonts-linuxlibertine texlive-bibtex-extra biblatex

script:
  - xelatex -interaction=nonstopmode semi_main.tex
  - xelatex -interaction=nonstopmode semi_main.tex

after_script:
  - echo "Semi" | mutt -a "semi_main.pdf" -s "semi" -- recipient@domain.com
