env:
  global:
    - TERM=dumb
    - GIT_AUTHOR_NAME="Alexander Sulfrian"
    - GIT_AUTHOR_EMAIL="alexander@sulfrian.net"
    - GIT_COMMITTER_NAME="Alexander Sulfrian"
    - GIT_COMMITTER_EMAIL="alexander@sulfrian.net"
    - secure: "UUlgNdMQDftSRBHpHPuYgxUWncjs4OhnL3BFCVWACwVqW5sBga6whnj/0HP9Fw61Jz/JBiQaG2ahk+voyfgIovZ8HvwOto1e4xOh8aWOmdYP7t3W7XiBOcG2ra24QZFVb6qxZqmibEP+drCLv2qYF0u1AEqYQfInruAEAOiVLFI="

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y texlive texlive-latex-extra texlive-generic-extra texlive-xetex texlive-lang-german fonts-linuxlibertine texlive-bibtex-extra biber

script:
  - xelatex -interaction=nonstopmode main.tex
  - biblatex main.tex
  - xelatex -interaction=nonstopmode main.tex
  - xelatex -interaction=nonstopmode main.tex